In [1]:
import pandas as pd
df = pd.read_csv("overture_NZ.csv")
df

,name,main_category,alternate_categories,lat,lng
0,Pearl Island,landmark_and_historical_building,"island,monument",-47.189700,167.706000
1,Kopeka River,river,NaN,-47.133333,167.933333
2,Toitoi River,river,NaN,-47.116667,167.983333
3,Lords River,river,NaN,-47.116667,168.150000
4,Rakeahua River,river,NaN,-46.983333,167.900000
...,...,...,...,...,...
137738,"Araraiti Bay, Whananaki",beach,structure_and_geography,-35.507186,174.466459
137739,Motutara Farm,campground,"farm,hotel",-35.505100,174.467260
137740,Whananaki North Doc Camp,campground,NaN,-35.501872,174.468942
137741,Otamure Bay Camp Site,campground,"beach,structure_and_geography",-35.491876,174.463143
137742,Poor Knights Islands Marine Reserve,national_park,"water_park,island",-35.481378,174.737203

In [2]:
df.main_category.value_counts().to_csv("categories.csv")

In [3]:
df.main_category.value_counts().head(50)

main_category
beauty_salon                        5155
cafe                                3597
hotel                               3446
park                                2755
community_services_non_profits      2664
automotive_repair                   2441
real_estate_agent                   1805
gym                                 1797
shopping                            1782
church_cathedral                    1730
school                              1707
sports_club_and_league              1535
professional_services               1520
landmark_and_historical_building    1493
coffee_shop                         1453
bar                                 1379
beach                               1374
real_estate                         1302
flowers_and_gifts_shop              1206
grocery_store                       1203
spas                                1186
preschool                           1152
river                               1093
active_life                         1062
restaurant                          1061
bakery                              1028
hospital                             976
car_dealer                           951
liquor_store                         928
gas_station                          921
clothing_store                       876
fast_food_restaurant                 837
dentist                              811
pharmacy                             800
bed_and_breakfast                    796
indian_restaurant                    764
engineering_services                 739
art_gallery                          731
education                            728
farm                                 713
elementary_school                    700
women's_clothing_store               671
barber                               666
naturopathic_holistic                663
martial_arts_club                    663
furniture_store                      661
pizza_restaurant                     639
lake                                 638
religious_organization               637
college_university                   625
Name: count, dtype: int64

In [4]:
# Add top level category from taxonomy
overture_taxonomy = pd.read_csv("https://raw.githubusercontent.com/OvertureMaps/schema/main/task-force-docs/places/overture_categories.csv", sep=";")
overture_taxonomy["Overture Taxonomy"] = overture_taxonomy["Overture Taxonomy"].apply(lambda s: s.strip("[]").split(","))
overture_taxonomy.set_index("Category code", inplace=True)
overture_taxonomy = overture_taxonomy["Overture Taxonomy"]
df["top_level_category"] = df.main_category.apply(lambda c: overture_taxonomy.get(c, [None])[0])
df

,name,main_category,alternate_categories,lat,lng,top_level_category
0,Pearl Island,landmark_and_historical_building,"island,monument",-47.189700,167.706000,attractions_and_activities
1,Kopeka River,river,NaN,-47.133333,167.933333,structure_and_geography
2,Toitoi River,river,NaN,-47.116667,167.983333,structure_and_geography
3,Lords River,river,NaN,-47.116667,168.150000,structure_and_geography
4,Rakeahua River,river,NaN,-46.983333,167.900000,structure_and_geography
...,...,...,...,...,...,...
137738,"Araraiti Bay, Whananaki",beach,structure_and_geography,-35.507186,174.466459,attractions_and_activities
137739,Motutara Farm,campground,"farm,hotel",-35.505100,174.467260,accommodation
137740,Whananaki North Doc Camp,campground,NaN,-35.501872,174.468942,accommodation
137741,Otamure Bay Camp Site,campground,"beach,structure_and_geography",-35.491876,174.463143,accommodation
137742,Poor Knights Islands Marine Reserve,national_park,"water_park,island",-35.481378,174.737203,attractions_and_activities

In [5]:
df.top_level_category.value_counts()

top_level_category
retail                                   23852
eat_and_drink                            16232
professional_services                     9388
attractions_and_activities                8900
active_life                               8681
beauty_and_spa                            8173
automotive                                7392
accommodation                             6650
education                                 6359
health_and_medical                        6073
public_service_and_government             6063
business_to_business                      4321
real_estate                               4136
arts_and_entertainment                    3076
home_service                              3075
religious_organization                    3027
travel                                    2669
financial_service                         2019
structure_and_geography                   1973
pets                                      1377
mass_media                                 430
private_establishments_and_corporates       62
Name: count, dtype: int64

In [19]:
mapping_dict = {}
for line in open("category_mapping.txt", encoding="utf8"):
  if " -> " not in line:
    continue
  overture_categories, resulting_category = line.strip().split(" -> ")
  for c in overture_categories.split(","):
    mapping_dict[c] = resulting_category
mapping_dict

{'Overture category': 'Overall category',
 'park': 'Parks',
 'sports_club_and_league': 'Sports Clubrooms (or sports facilities)',
 'sports_and_recreation_venue': 'Sports Clubrooms (or sports facilities)',
 'library': 'Libraries',
 'art_gallery': 'Arts & Crafts',
 'arts_and_crafts': 'Arts & Crafts',
 'bus_station': 'Bus/train/ferry stops',
 'train_station': 'Bus/train/ferry stops',
 'supermarket': 'Supermarkets',
 'convenience_store': 'Dairies',
 'fruits_and_vegetables': 'Fruit & Veg',
 'gas_station': 'Service Stations',
 'banks': 'Banks, ATM & money lenders',
 'atms': 'Banks, ATM & money lenders',
 'mortgage_lender': 'Banks, ATM & money lenders',
 'laundromat': 'Laundromats',
 'cafe': 'CafÃ©',
 'thrift_store': 'Op shops',
 'shopping_center': 'Mall',
 'preschool': 'Early childhood education',
 'day_care_preschool': 'Early childhood education',
 'elementary_school': 'Primary schools',
 'middle_school': 'Intermediate/full primary schools',
 'high_school': 'Secondary schools',
 'vocational_and_technical_school': 'Training institutions (non-degree)',
 'college_university': 'Training institutions (degree)',
 'health_and_medical': 'GPs/M?ori primary care',
 'family_practice': 'GPs/M?ori primary care',
 'pharmacy': 'Pharmacies',
 'emergency_room': 'A&E',
 'hospital': 'Hospitals',
 'dentist': 'Oral healthcare services',
 'general_dentistry': 'Oral healthcare services',
 'mosque': 'Religious institutions/places of worship',
 'religious_organization': 'Religious institutions/places of worship',
 'church_cathedral': 'Religious institutions/places of worship',
 'catholic_church': 'Religious institutions/places of worship',
 'baptist_church': 'Religious institutions/places of worship',
 'anglican_church': 'Religious institutions/places of worship',
 'pentecostal_church': 'Religious institutions/places of worship',
 'evangelical_church': 'Religious institutions/places of worship',
 'community_center': 'Community centres/halls',
 'social_service_organizations': 'CABs & other social services',
 'betting_center': 'TAB',
 'liquor_store': 'Licensed premises/alcohol outlets',
 'fast_food_restaurant': 'Fast food outlets'}

In [20]:
df["mapped_category"] = df.main_category.apply(lambda c: mapping_dict.get(c, "other"))
df["mapped_category"].value_counts()

mapped_category
other                                       112412
CafÃ©                                          3597
Religious institutions/places of worship      2910
Parks                                         2755
Sports Clubrooms (or sports facilities)       1941
Early childhood education                     1711
Arts & Crafts                                 1130
Hospitals                                      976
Licensed premises/alcohol outlets              928
Service Stations                               921
Oral healthcare services                       879
Fast food outlets                              837
Pharmacies                                     800
GPs/M?ori primary care                         725
Primary schools                                700
Training institutions (degree)                 625
Supermarkets                                   542
Community centres/halls                        389
Libraries                                      378
Dairies                                        376
Fruit & Veg                                    324
Secondary schools                              305
Bus/train/ferry stops                          265
Banks, ATM & money lenders                     241
Mall                                           234
Op shops                                       232
CABs & other social services                   214
Laundromats                                    212
Intermediate/full primary schools              113
Training institutions (non-degree)              58
A&E                                             10
TAB                                              3
Name: count, dtype: int64